// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMPkdN8s56jb8JEeoLd87yRdAYuwIDtY',
    appId: '1:297499782303:web:052f3b07d744b3929886aa',
    messagingSenderId: '297499782303',
    projectId: 'gelecek-c262e',
    authDomain: 'gelecek-c262e.firebaseapp.com',
    storageBucket: 'gelecek-c262e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9AyR3ingGxoEHqcDPK4xIeDJaxzlc5s',
    appId: '1:297499782303:android:e909cdedddbef4779886aa',
    messagingSenderId: '297499782303',
    projectId: 'gelecek-c262e',
    storageBucket: 'gelecek-c262e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDtrNmMOMY68c7v-73pSq_00LWydxCSU',
    appId: '1:297499782303:ios:d49fa7af2935cac19886aa',
    messagingSenderId: '297499782303',
    projectId: 'gelecek-c262e',
    storageBucket: 'gelecek-c262e.firebasestorage.app',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDtrNmMOMY68c7v-73pSq_00LWydxCSU',
    appId: '1:297499782303:ios:d49fa7af2935cac19886aa',
    messagingSenderId: '297499782303',
    projectId: 'gelecek-c262e',
    storageBucket: 'gelecek-c262e.firebasestorage.app',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcMPkdN8s56jb8JEeoLd87yRdAYuwIDtY',
    appId: '1:297499782303:web:f30b29fb0ca17b309886aa',
    messagingSenderId: '297499782303',
    projectId: 'gelecek-c262e',
    authDomain: 'gelecek-c262e.firebaseapp.com',
    storageBucket: 'gelecek-c262e.firebasestorage.app',
  );

}